// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "User CRUD": Application Resource Href Factories
//
// Command:
// $ goagen
// --design=GolandProject/goa-sample/src/design
// --out=$(GOPATH)/src/GolandProject/goa-sample/src
// --version=v1.3.1

package app
